# This is snap sourcing itself if not present
[ -f "$_loc"/zsh/plugins/zsh-snap/znap.zsh ] \
  || git clone \
  --depth 1 \
  -- https://github.com/marlonrichert/zsh-snap.git \
  "$_loc"/zsh/plugins/zsh-snap

. "$_loc"/zsh/plugins/zsh-snap/znap.zsh

# Plugins{{{
[ -f "$_loc"/zsh/plugins/zsh-snap/znap.zsh ] && {
# ohmyzsh{{{
  znap install ohmyzsh/ohmyzsh
  check sudo && znap source ohmyzsh/ohmyzsh plugins/sudo
  znap source ohmyzsh/ohmyzsh plugins/colored-man-pages
# }}}
  # zvm {{{
  export ZVM_VI_EDITOR=$EDITOR
  export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BEAM
  export ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
  znap source jeffreytse/zsh-vi-mode
  # }}}
  znap source zsh-users/zsh-autosuggestions
  znap source z-shell/F-Sy-H
  znap source chrissicool/zsh-256color
  znap source zsh-users/zsh-completions
  znap source MichaelAquilina/zsh-you-should-use
  check doas && znap source Senderman/doas-zsh-plugin
}
# }}}

# prompt{{{
check starship && {
  znap eval starship 'starship init zsh --print-full-init'
  prompt_starship_precmd
  check colorscript && colorscript -r
  znap prompt starship
}
# }}}

check gtasks && znap fpath _gtasks 'gtasks completion zsh'
check gh && znap fpath _github 'gh completion -s zsh'
check trash && znap fpath _trash 'trash --print-completion zsh'

zvm_after_init_commands+=('[ -f "$_loc"/zsh/rc ] && . "$_loc"/zsh/rc')
